### ISSUE TITLE
docs: What is brick.yaml repository field?

### ISSUE THREAD

**Issue by BGM-109** [brick-hub/brickhub.dev#63]
**Description**

halo

I encountered this phrase while publishing my brick.

**Malformed bundle.
The brick.yaml repository field must be provided.**

```
name: name
description: description

version: 0.1.0+2

environment:
  mason: ">=0.1.0-dev.26 <0.1.0"

vars:
  name:
    type: string
    description: feature name
    default: coffee
    prompt: What is ur feature name?
  hasNotifier:
    type: boolean
    description: Make a hasNotifier widget
    default: true
    prompt: has Notifier?
  url:
    type: string
    description: base url
    default: none
    prompt: What is ur base url?
```

Whats going on bros?
